/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/card/action.vue')['default']
    Card: typeof import('./src/components/card/card.vue')['default']
    CardProperty: typeof import('./src/components/card-property.vue')['default']
    CardStatus: typeof import('./src/components/card-status.vue')['default']
    Heading: typeof import('./src/components/card/heading.vue')['default']
    Link: typeof import('./src/components/link.vue')['default']
    LinkButton: typeof import('./src/components/link-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SColorMode: typeof import('./src/components/SColorMode.vue')['default']
    SCountryCode: typeof import('./src/components/SCountryCode.vue')['default']
    SDisclosureAction: typeof import('./src/components/disclosure/SDisclosureAction.vue')['default']
    SDisclosureBlock: typeof import('./src/components/disclosure/SDisclosureBlock.vue')['default']
    SDisclosurePanel: typeof import('./src/components/disclosure/SDisclosurePanel.vue')['default']
    SPanel: typeof import('./src/components/SPanel.vue')['default']
    SProfile: typeof import('./src/components/SProfile.vue')['default']
    SSidebar: typeof import('./src/components/layout/SSidebar.vue')['default']
    STabsDisplay: typeof import('./src/components/tabs/STabsDisplay.vue')['default']
    STabsItem: typeof import('./src/components/tabs/STabsItem.vue')['default']
    STabsList: typeof import('./src/components/tabs/STabsList.vue')['default']
    STabsPanel: typeof import('./src/components/tabs/STabsPanel.vue')['default']
    STopbar: typeof import('./src/components/layout/STopbar.vue')['default']
    STopbarNeo: typeof import('./src/components/layout/STopbarNeo.vue')['default']
    Tabs: typeof import('./src/components/card/tabs.vue')['default']
  }
}
